root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  include_ext = ["go"]
  exclude_dir = ["tmp", "ui"]
  delay = 1000

[log]
  time = false

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "green"

[misc]
  clean_on_exit = true
